name: Score Sense Server Builder

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle 8.8
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.8"

      - name: Grant Execution Authority to Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test -PartefactVersion=${{ github.event.release.tag_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \ 
          --build-arg APP_VERSION=${{ github.event.release.tag_name }} \
          --tag ghcr.io/onixbyte-business/score-sense/score-sense-db:${{ github.event.release.tag_name }} --push .
